### ISSUE TITLE
Dev build fails with Error: spawn grommet ENOENT

### ISSUE THREAD

**Issue by avirgvd** [grommet/grommet-sample#22]
I am facing build issues after migrating my GrommetV1 application to GrommetV2. I tried grommet-sample and see same issue for 'npm run dev'. 

**My env:**
node v14.16.1
npm  v6.14.12
OS: MacOS Big Sur 11.2.3

**The command output:**

```
% npm run dev

> grommet-sample@0.2.0 dev /Users/govind/experiments/grommet-sample
> cross-env NODE_ENV=development grommet pack

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn grommet ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn grommet',
  path: 'grommet',
  spawnargs: [ 'pack' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grommet-sample@0.2.0 dev: `cross-env NODE_ENV=development grommet pack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grommet-sample@0.2.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/govind/.npm/_logs/2021-04-18T05_52_17_387Z-debug.log
```

**Comment by avirgvd** [comment]
grommet-cli is no more available for React 16 and later. Is webpack good alternative?
Please suggest how the grommet cli dependencies be resolved in package.json.

Is it good idea to change the scripts entries in package.json 
from:
    "dev": "cross-env NODE_ENV=development grommet",
to:
    "dev": "cross-env NODE_ENV=development webpack",

**Comment by ShimiSun** [comment]
When using grommet v2, you should no longer need to use `grommet-cli`, and its functionality could be removed altogether. You should be able to remove it from your package.json
